spring:
  application:
    name: jukebox

  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            client-name: spotify
            scope:
              - user-read-playback-state
              - user-modify-playback-state
            authorization-grant-type: authorization_code
            redirect-uri: http://[::1]:8080/login/oauth2/code/spotify

        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id

  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
      - classpath:db/seed
    fail-on-missing-locations: true

  jpa:
    hibernate:
      ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
          highlight_sql: true
  
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT}

logging:
  level:
    com.jukebox: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

jwt:
  secret: ${JWT_SECRET}
  access-expires-in: 120
  refresh-expires-in: 3600
  issuer: jukebox

endpoint:
  frontend:
    domain: ${FRONTEND_DOMAIN}
    o-auth2-callback: /sign-in/callback



